### ISSUE TITLE
Link to example issues from readme ?

### ISSUE THREAD

**Issue by Carreau** [xarray-contrib/issue-from-pytest-log#20]
Thanks for your comment on https://github.com/scientific-python/specs/issues/181, Looking at the readme I'd love to see the kind of issue it opens !

**Comment by keewis** [comment]
That's a good point!

I have a bunch of these [here](https://github.com/keewis/reportlog-test/issues) (I used that repo to debug the action), but you can also look at [xarray's issue tracker](https://github.com/pydata/xarray/issues) to see a few more realistic examples.
