### ISSUE TITLE
Error parsing log message 

### ISSUE THREAD

**Issue by jrbourbeau** [xarray-contrib/issue-from-pytest-log#25]
Over in `dask/dask` we started getting this error recently:

```python
Traceback (most recent call last):
Parsing logs ...
  File "/home/runner/work/_actions/xarray-contrib/issue-from-pytest-log/v1.2.6/parse_logs.py", line 233, in <module>
    preformatted = [preformat_report(report) for report in failed]
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/_actions/xarray-contrib/issue-from-pytest-log/v1.2.6/parse_logs.py", line 233, in <listcomp>
    preformatted = [preformat_report(report) for report in failed]
                    ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/miniconda3/envs/test-environment/lib/python3.11/functools.py", line 909, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/runner/work/_actions/xarray-contrib/issue-from-pytest-log/v1.2.6/parse_logs.py", line 92, in _
    message = report.longrepr.chain[0][1].message
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'message'
```

See [this CI build](https://github.com/dask/dask/actions/runs/6646641106/job/18060524574) for a concrete example

**Comment by keewis** [comment]
I can't seem to reproduce this locally. Do you know what changed since then that made this go away? I suspect there is a different type of report, but to be able to confirm that (or just to debug) I'd need to have the output of `pytest-reportlog` that would trigger this.

**Comment by jrbourbeau** [comment]
Huh, I just checked again and things are working now. Issues that fix themselves magically are the best kind of issues I guess! 

Closing -- sorry for the noise @keewis

**Comment by keewis** [comment]
Or the worst, since you never know when they will reappear. However, I guess in that case we can just open a new issue.

**Comment by Zeitsperre** [comment]
I think I've been seeing this for a few weeks now: https://github.com/Ouranosinc/xclim/actions/runs/6937279511/job/18871034404

Should I reopen the issue here or make a new issue?

**Comment by dcherian** [comment]
Yes, there's a new record type for warnings, which might explain why its flaky.

I ended up adding this
```python
    cls = report_types.get(record["$report_type"])
    if cls is None:
        warnings.warn(f"unknown report type: {record['$report_type']} for record: \n\n {record}\n\n")
        return None
```
instead of the existing ValueError:
https://github.com/xarray-contrib/issue-from-pytest-log/blob/327614c6c91fd37ef5025caafe131fa455574768/parse_logs.py#L63-L64
to ignore unknown report types. The specific one for me was `WarningMessage`

**Comment by dcherian** [comment]
oh the error i had is not the one being discussed here unfortunately :/

**Comment by keewis** [comment]
Feel free to open a new issue in that case! It is true though that I totally forgot to check that the script still works after my PR to `pytest-reportlog` got accepted.

For reference, here's the [log from `xclim`'s test suite](https://github.com/xarray-contrib/issue-from-pytest-log/files/13428901/xclim-2023-11-21.json) that triggers the `'NoneType' object has no attribute 'message'` error from the original report (or hopefully it is that error).
